seed: 0
gpu_id: # empty for cpu

tasks:
    indices:
        - [0, 5]
        - [2, 7]
    labels: [0, 1]
    mixing: [1, 0.5]

training:
    total_epochs: 5
    switch_epoch: 3
    learning_rate: 0.01
    batch_size: 1
    loss_fn: cross_entropy

network:
    input_dimension: 1024
    hidden_dimension: 8
    output_dimension: 1
    nonlinearity: relu
    biases: False

plotting:
    xlabel: epoch
    smoothing: 3